 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/gradle'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-boot:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/gradle'
   args: ['push', 'gcr.io/$PROJECT_ID/spring-boot:$COMMIT_SHA']

 # deploys the new version of our container image in the Kubernetes Engine cluster.
    #The env takes a list of environment variables to be used when running the step. The are KEY=VALUE.
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args: ['apply' , '-f' , 'deployment.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=<gke_cluster_zone/region>'
    - 'CLOUDSDK_CONTAINER_CLUSTER=<gke_cluster_name>'

 images:
 - 'gcr.io/$PROJECT_ID/spring-boot:$COMMIT_SHA'
