apiVersion: v1
kind: Deployment
metadata:
  name: hello-enset
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-enset
        visualize: "true"
    spec:
      containers:
      - name: hello-enset-pod
        image: gcr.io/my-project-2-339811/github.com/kgassab1/spring_boot
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: hello-enset-service
spec:
  selector:
    app: hello-enset
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
